variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test

build:linux:
  image: alpine:latest
  tags:
    - linux
  stage: build
  before_script:
    - apk add --update g++ make cmake linux-headers libcap-dev
  script:
    - make 
  artifacts:
    paths:
      - "lokinet"

build:windows:
  image: ubuntu:latest
  tags:
    - windows
  stage: build
  before_script:
    - apt update && apt install build-essential cmake mingw-w64 mingw-w64-tools
  script:
    - make windows STATIC_LINK=ON AVX2=OFF JSONRPC=OFF
  artifacts:
    paths:
      - "lokinet.exe"
