variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test

build:linux:
  image: alpine:latest
  tags:
    - linux
  stage: build
  before_script:
    - apk add --update g++ make cmake linux-headers libsodium-dev ninja libcap-dev
  script:
    - make 
  artifacts:
    paths:
      - "lokinet"

